name: Sync Release APKs # 将 'Name' 改为 'name'

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  download-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Download and commit APKs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config http.postBuffer 524288000
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          REPO="kiwibrowser/src.next"
          START_YEAR=2025
          END_YEAR=2015
          mkdir -p releases

          for YEAR in $(seq $START_YEAR -1 $END_YEAR); do
            echo "=== 下载年份 $YEAR 的 Release ==="
            mkdir -p "releases/$YEAR"
            page=1
            total_year=0

            while true; do
              response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/releases?per_page=100&page=$page")

              if echo "$response" | jq -e 'length == 0' > /dev/null; then
                break
              fi

              echo "$response" | jq -r '.[] | @base64' | while read release; do
                _jq() { echo "$release" | base64 -d | jq -r "$1"; }
                published=$(echo $(_jq '.published_at') | cut -d'-' -f1)

                if [ "$published" != "$YEAR" ]; then
                  continue
                fi

                tag=$(_jq '.tag_name')
                echo "Processing release $tag ($YEAR)"
                assets=$(_jq '.assets | length')

                for i in $(seq 0 $((assets-1))); do
                  name=$(echo "$release" | base64 -d | jq -r ".assets[$i].name")
                  url=$(echo "$release" | base64 -d | jq -r ".assets[$i].browser_download_url")
                  if [[ "$name" == *.apk ]]; then
                    echo "Downloading $name ..."
                    curl -L -o "releases/$YEAR/$name" "$url"
                    total_year=$((total_year+1))
                  fi
                done
              done
              page=$((page+1))
            done

            echo "✅ $YEAR 年下载完成，共下载 $total_year 个 APK"

            files=$(ls "releases/$YEAR"/*.apk 2>/dev/null || true)
            if [ -n "$files" ]; then
              batch=0
              for f in $files; do
                git add "$f"
                batch=$((batch+1))
                if [ $batch -ge 4 ]; then
                  git commit -m "chore: add APKs for $YEAR"
                  git push
                  batch=0
                fi
              done
              if [ $batch -gt 0 ]; then
                git commit -m "chore: add remaining APKs for $YEAR"
                git push
              fi
            fi

            echo "清理临时日志..."
            rm -f /home/runner/work/_temp/*.log || true
          done
